name: customer
description: "Food Delivery Customer App - Node.js Backend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.7.2
  provider: ^6.1.2
  
  # Network & API
  dio: ^5.4.0
  socket_io_client: ^2.0.3
  connectivity_plus: ^6.0.5
  http: ^1.3.0
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.0
  
  
  # UI Components
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  flutter_easyloading: ^3.0.5
  flutter_html: any
  flutter_local_notifications: ^18.0.1
  dotted_border: ^2.1.0
  badges: ^3.1.2
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1
  pin_code_fields: ^8.0.1
  qr_flutter: ^4.1.0
  qr_code_dart_scan: ^0.9.11
  bottom_picker: ^2.11.1
  timelines_plus: ^1.0.6
  date_picker_timeline: ^1.2.6
  syncfusion_flutter_datepicker: ^28.2.9
  timer_count_down: ^2.2.2
  
  # Maps & Location
  google_maps_flutter: ^2.10.1
  geolocator: any
  location: ^8.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  google_maps_place_picker_mb: ^3.1.2
  osm_nominatim: ^3.0.1
  flutter_osm_plugin: ^1.3.6
  map_launcher: ^3.5.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  crypto: ^3.0.6
  clipboard: ^0.1.3
  share_plus: ^10.1.4
  in_app_review: ^2.0.10
  country_code_picker: ^3.2.0
  flutter_email_sender: ^7.0.0
  mailer: ^6.4.1
  video_compress: ^3.1.4
  video_player: ^2.9.3
  googleapis_auth: ^1.6.0

dependency_overrides:
  webview_flutter: ^4.7.0
  google_api_headers: ^4.4.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/

  fonts:
    - family: Urbanist-Black
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf

    - family: Urbanist-Bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf

    - family: Urbanist-ExtraBold
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf

    - family: Urbanist-ExtraLight
      fonts:
        - asset: assets/fonts/Urbanist-ExtraLight.ttf

    - family: Urbanist-Light
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf

    - family: Urbanist-Medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf

    - family: Urbanist-Regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf

    - family: Urbanist-SemiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf

    - family: Urbanist-Thin
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf
